### ISSUE TITLE
Free-GPGMail 2021.3.1 is out

### ISSUE THREAD

**Issue by bnavigator** [EivindArvesen/Free-GPGMail-Tap#1]
There is a new release, which tries to add compatibility with macOS 12.3 as well as with older versions which do not handle the notarization well.

**Comment by EivindArvesen** [comment]
Updated to v2021.3.1 and fixed install-issues (see [issue](https://github.com/Free-GPGMail/Free-GPGMail/issues/41#issuecomment-1074098471)).
